# Generated by Django 4.1.4 on 2022-12-19 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="Untitled",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "separator",
                    models.TextField(
                        choices=[
                            (",", "Comma(,)"),
                            (";", "Semilicon(;)"),
                            ("\t", "Tab(\t)"),
                            (" ", "Space( )"),
                            ("|", "Pipe(|)"),
                        ],
                        default=",",
                        max_length=1,
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        choices=[
                            ("''", "Single-quote('')"),
                            ('""', 'Double-quote("")'),
                        ],
                        default='""',
                        max_length=2,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Processing.."), (1, "Ready!")], default=0
                    ),
                ),
                ("rows", models.PositiveIntegerField(null=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_ds",
                        to="fakedata.fakeschema",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=25)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            (
                                "Full_name",
                                "Full name (a combination of first name and last name)",
                            ),
                            ("Job", "Job"),
                            ("Email", "Email"),
                            ("Domain", "Domain name"),
                            ("Phone", "Phone number"),
                            ("Company", "Company name"),
                            (
                                "Text",
                                "Text (with a specified range for a number of sentences)",
                            ),
                            ("Integer", "Integer (with specified range)"),
                            ("Address", "Address"),
                            ("Date", "Date"),
                        ],
                        max_length=25,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column",
                        to="fakedata.fakeschema",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
