# Generated by Django 4.1.4 on 2022-12-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fakedata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fakeschema",
            options={"ordering": ["-created"]},
        ),
    ]
